### ISSUE TITLE
Conflict between "search by map" and dropdowns

### ISSUE THREAD

**Issue by myersnews** [TheLens/land-records#62]
Do a search, click "search by map." Then choose a ZIP. The two conflict. When you do that, it should de-select the search by map option.

**Comment by ThomasThoren** [comment]
There's still a small piece of this that might not be perfect yet, but I think it mostly works the way the users expect, so I'm moving this down in priority for now.

It will still search both by bounds and by the zip/neighborhood if you have a zip/neighborhood selected and then turn on "search by map" and move the map without first clicking "Search." If you pan away from that current zip/neighborhood, this won't show anything obviously because the map bounds don't overlap the zip/neighborhood.
