### ISSUE TITLE
Update scraper and database layout to check for permanent/temporary sales

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/land-records#94]
Scraper will need to check if date is in permanent or temporary range, then flag accordingly in the database. If temporary, add asterisk on front-end denoting temporary status.

Every scrape, check if permanent range includes dates with temporary flag. If so, re-scrape those dates, delete their old records in database (temporary info), and insert new records (permanent info).

**Comment by ThomasThoren** [comment]
The new scraper is chugging away on the server and storing the new HTML in a separate directory.

**Comment by myersnews** [comment]
So we are all up to date? Any way to know how many changed?

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Feb 25, 2015, at 11:32 PM, Thomas Thoren <notifications@github.com>
wrote:

Closed #94 <https://github.com/TheLens/land-records/issues/94>.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/land-records/issues/94#event-242269943>.

**Comment by ThomasThoren** [comment]
Not quite up to date yet. I closed this because the scraper code is finished, the database layout is ready and the checks for permanent vs. temporary are in place. Once the scraper finishes (sometime early tomorrow morning), I'll build the new database and swap out the current one.

**Comment by myersnews** [comment]
10-4.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Feb 25, 2015, at 11:44 PM, Thomas Thoren <notifications@github.com>
wrote:

Not quite up to date yet. I closed this because the scraper code is
finished, the database layout is ready and the checks for permanent vs.
temporary are in place. Once the scraper finishes (sometime early tomorrow
morning), I'll build the new database and swap out the current one.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/land-records/issues/94#issuecomment-76125734>.
